### ISSUE TITLE
CLA examples

### ISSUE THREAD

**Issue by osullivryan** [twmacro/pyyeti#1]
First, just wanted to say this is awesome. Seriously. **Amazing**. 

Second, I'm really interested in the CLA functionality, but I'm not to sure how to apply it. Could you provide an example (with an OP2) on this?

Thanks!

**Comment by twmacro** [comment]
@osullivryan I'm so sorry I didn't see your note until now! I just assumed I would get an email if anyone opened an issue. 

First, thank you very much! :) Second, I intend to write a tutorial on exactly this, but for now, probably the best example is in the tests directory:

https://github.com/twmacro/pyyeti/blob/master/tests/test_cla.py

Start with the "test_transfer_orbit_cla()" function. It runs 3 events and demos a lot of the functionality of the code. The events I made up are:

 - TOES: Transfer orbit engine start
 - OWLAB: Oil and water laboratory
 - TOECO: Transfer orbit engine cutoff

All the files you need are included. I hope this helps and I apologize I didn't get your note before now!!

Thanks for your interest!

**Comment by osullivryan** [comment]
@twmacro , thanks for the response. I'll take a look and shoot you a message if I have any questions. First glance the test looks pretty explanatory. I'll also look out for your tutorial!
