### ISSUE TITLE
Modal Complexity Factor (MCF)

### ISSUE THREAD

**Issue by Ayubirad** [twmacro/pyyeti#14]
Dear @twmacro ,

In my opinion, I believe that the complexity value, commonly referred to as the **Mode Complexity Factor (MCF)**, holds greater merit in guiding users to distinguish between physical modes and spurious ones than the currently implemented realness value. To further elaborate, I have provided a link below that explores this perspective in more detail:

https://www.svibs.com/resources/ARTeMIS_Modal_Help_v7/Generic%20Complexity%20Plot.html

Thank you for your time and consideration.
Ayubirad

**Comment by twmacro** [comment]
Hi @Ayubirad,

I will definitely take a look. Thank you!

Best regards,
Tim

**Comment by twmacro** [comment]
Hi @Ayubirad,

It turns out that MCF = 1-MPC, an indicator already included in the pyYeti ERA routine! :-) It is a great measure. Thank you for the link though ... I plan to simplify the equations in pyYeti in a similar fashion.

Best regards,
Tim
