### ISSUE TITLE
Some comments on stabilization diagram

### ISSUE THREAD

**Issue by Ayubirad** [twmacro/pyyeti#15]
Dear @twmacro 

I wanted to bring your attention to a well-written paper that I recently came across regarding modal identification. It proposes two modal indicators, the Modal Similarity Index (MSI) and Mode Energy Level (MEL), which can help remove some spurious modes. I believe this paper could be of interest to you and could even be implemented with relative ease. Please find the link below for your reference. Thank you for your time.

https://www.sciencedirect.com/science/article/abs/pii/S0022460X14002041

Best regards,
Ayubirad

**Comment by twmacro** [comment]
Hi @Ayubirad,

Thank you so much for the info! :-) I have the paper now and will definitely look it over.

Best regards,
Tim
