### ISSUE TITLE
no attribute isspmatrix

### ISSUE THREAD

**Issue by joshayers** [twmacro/pyyeti#20]
When running tests/test_ode.py, I get a large number of errors.

One of the errors occurs in `test_newmark_nonlinear`.  The error occurs in `expmint._solve_P_Q_2`, on line 649.  The `mf.isspmatrix` function doesn't exist.  The `mf` module is imported from `scipy.sparse.linalg._matfuncs`.

If I replace `mf.isspmatrix` with `scipy.sparse.isspmatrix`, the tests pass.

I'm running Python 3.11.4, NumPy 1.25.1, and SciPy 1.11.1.  I can make the fix, but I wasn't sure if this was written as it was because of backwards compatibility.

**Comment by twmacro** [comment]
Thanks for the report, @joshayers! :-) I'll play with this ... see if your fix works for versions back to 1.9.1.

**Comment by twmacro** [comment]
Fixed version 1.3.3. Thank you, @joshayers! :-)
