### ISSUE TITLE
ERA for modal analysis

### ISSUE THREAD

**Issue by Ayubirad** [twmacro/pyyeti#6]
First of all, thanks for this wonderful package. If at all feasible, please consider the following suggestions for improving this brilliant package: 
1. Could you also add the Natural Excitation Technique (NExT)?
2. An improved consistency indicator called CMI from the observability matrix (CMI_O) is suggested, which is also consistent under high damping ratios [1].

[1] Yun, G. J., Lee, S. G., & Shang, S. (2012). An improved mode accuracy indicator for Eigensystem Realization Analysis (ERA) techniques. KSCE Journal of Civil Engineering, 16, 377-387.

**Comment by twmacro** [comment]
Thank you very much @Ayubirad for your input! :) I will add these items to my to-do list.

I know of NExT, but I'll need to educate myself more on this technique before I can code it up nicely. I'm looking forward to it though.

I haven't heard of this indicator and am pretty excited to check it out! Many thanks for the paper. I have it now and have already read the abstract. Sounds like a very nice addition! 

Note that I probably won't get to this for a month or two, just FYI.

Best Regards,
Tim

**Comment by Ayubirad** [comment]
Dear @twmacro 

Thanks for this brilliant package. Is it possible to obtain mode shapes using `Eigensystem Realization Algorithm`? 

Best regards
Ayubirad

**Comment by twmacro** [comment]
Hi @Ayubirad,

I added one of these two features (the EMACO / CMIO indicators). Let me know what you think! The routine has a number of other enhancements as well.

As for NExt, I'm playing with cross-correlations, but using them seems tricky. Of course, you can do your own cross-correlations, trim them, and give them to ERA to see what happens. I do plan to continue experimenting, but I think I'll try to find some real data before playing too much more. NExt may take a bit more time.  

Best regards,
Tim

**Comment by Ayubirad** [comment]
Dear @twmacro 

Thanks, actually I'm working with the acceleration responses along a truss bridge due to train passages. For the purpose of modal identification from the free-decay part of the responses, I've been working with SSI-COV/ DATA, and now with your help, ERA. Can I have your email address for better communication?

Best regards,
Ayubirad

**Comment by twmacro** [comment]
Hi @Ayubirad,

My email is my github id at gmail.com. I won't make any promises, but I'd like to try to help out if I can. Just know that this isn't my day job, but I enjoy playing with this stuff when I find time. :-)

Best regards,
Tim

**Comment by Ayubirad** [comment]
Dear @twmacro 

I wanted to reach out and express my sincere gratitude for implementing NExT-ERA. Please keep up the excellent work, and thank you again for your dedication and efforts.

Best regards,
Ayubirad

**Comment by twmacro** [comment]
Hi @Ayubirad,

I'm glad you noticed the new function and got good results with it already! :-) That's great to hear!

I've got the stabilization diagram on my to-do list, and I've even made a couple updates to ERA to prepare for it. Stay tuned! (It might be several weeks ... there are other items I want to work as well.)

Thanks for your input!!
Best regards,
Tim

**Comment by Ayubirad** [comment]
Hi @twmacro,

I hope this message finds you well! It's been a while since we last touched base—I hope all is going well.

I wanted to reach back out to you regarding the stabilization diagram we discussed previously. I remember you mentioned you had it on your to-do list and were making some updates to the ERA in preparation for it. I'm really excited about the potential improvements this could bring!

Could you share any updates on the progress of the stabilization diagram? I'm keen to see how it's coming along.

Thanks so much for your dedication and hard work. Looking forward to your response.

Best regards,
Ayubirad

P.S. Here's the DOI of a sample paper on stabilization diagram:

Innovative stabilization diagram for automated structural modal identifcation based on ERA and hierarchical cluster analysis
[](https://doi.org/10.1007/s13349-021-00514-8)
